//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int articlesID { get; set; }
        public string atlName { get; set; }
        public Nullable<int> scientistID { get; set; }
        public Nullable<int> nationID { get; set; }
        public string atlSummary { get; set; }
        public Nullable<int> keyID { get; set; }
        public Nullable<int> magazineID { get; set; }
        public string Point { get; set; }
        public Nullable<int> statusID { get; set; }
        public string atlLink { get; set; }
        public Nullable<int> typeID { get; set; }
        public string atlPublication { get; set; }
        public Nullable<int> fieldID { get; set; }
        public string atlNumber { get; set; }
        public string atlPageToPage { get; set; }
        public Nullable<System.DateTime> atlPublicationDate { get; set; }
        public Nullable<System.DateTime> atlCreateDate { get; set; }
        public Nullable<System.DateTime> atlModifierDate { get; set; }
        public Nullable<int> atlCreateUser { get; set; }
        public Nullable<int> atlModifierUser { get; set; }
    }
}
