//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtType
    {
        public int typeID { get; set; }
        public string typName { get; set; }
        public string typDescription { get; set; }
        public Nullable<System.DateTime> typCreateDate { get; set; }
        public Nullable<System.DateTime> typModifierDate { get; set; }
        public Nullable<int> typCreateUser { get; set; }
        public Nullable<int> typModifierUser { get; set; }
    }
}
