//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public int classifiID { get; set; }
        public string clsName { get; set; }
        public string clsDescription { get; set; }
        public Nullable<System.DateTime> clsCreateDate { get; set; }
        public Nullable<System.DateTime> clsModifierDate { get; set; }
        public Nullable<int> clsCreateUser { get; set; }
        public Nullable<int> clsModifierUser { get; set; }
        public Nullable<int> clsOrder { get; set; }
    }
}
