//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Council
    {
        public int councilID { get; set; }
        public string cniName { get; set; }
        public string cniChairman { get; set; }
        public string cniSecretary { get; set; }
        public string cniReviewer { get; set; }
        public string cniComment { get; set; }
    }
}
