//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public int degreeID { get; set; }
        public string degName { get; set; }
        public string degDescription { get; set; }
        public Nullable<System.DateTime> degCreateDate { get; set; }
        public Nullable<System.DateTime> degModifierDate { get; set; }
        public Nullable<int> degCreateUser { get; set; }
        public Nullable<int> degModifierUser { get; set; }
    }
}
