//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int fieldID { get; set; }
        public string fieName { get; set; }
        public string fieDescription { get; set; }
        public Nullable<System.DateTime> fieCreateDate { get; set; }
        public Nullable<System.DateTime> fieModifierDate { get; set; }
        public Nullable<int> fieCreateUser { get; set; }
        public Nullable<int> fieModifierUser { get; set; }
    }
}
