//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intro
    {
        public int introID { get; set; }
        public string itdName { get; set; }
        public string itdSummary { get; set; }
        public string itdIcon { get; set; }
        public Nullable<System.DateTime> itdCreateDate { get; set; }
        public Nullable<System.DateTime> itdModifierDate { get; set; }
        public Nullable<int> itdCreateUser { get; set; }
        public Nullable<int> itdModifierUser { get; set; }
    }
}
