//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nation
    {
        public int nationID { get; set; }
        public string natName { get; set; }
        public string natTwoCode { get; set; }
        public string natThreeCode { get; set; }
        public string natDescription { get; set; }
        public Nullable<System.DateTime> natCreateDate { get; set; }
        public Nullable<System.DateTime> natModifierDate { get; set; }
        public Nullable<int> natCreateUser { get; set; }
        public Nullable<int> natModifierUser { get; set; }
    }
}
