//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int placeID { get; set; }
        public string plaName { get; set; }
        public string plaDescription { get; set; }
        public Nullable<System.DateTime> plaCreateDate { get; set; }
        public Nullable<System.DateTime> plaModifierDate { get; set; }
        public Nullable<int> plaCreateUser { get; set; }
        public Nullable<int> plaModifierUser { get; set; }
    }
}
