//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scientist
    {
        public int scientistID { get; set; }
        public string sctFirstName { get; set; }
        public string sctLastName { get; set; }
        public string sctSex { get; set; }
        public Nullable<System.DateTime> sctBirthday { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<int> degreeID { get; set; }
        public Nullable<int> unitID { get; set; }
        public Nullable<int> fieldID { get; set; }
        public string sctWorkingProcess { get; set; }
        public string sctResult { get; set; }
        public Nullable<int> sctForeignID { get; set; }
        public string sctAddress { get; set; }
        public string sctPhone { get; set; }
        public string sctEmail { get; set; }
        public Nullable<System.DateTime> sctCreateDate { get; set; }
        public Nullable<System.DateTime> sctModifierDate { get; set; }
        public Nullable<int> sctCreateUser { get; set; }
        public Nullable<int> sctModifierUser { get; set; }
    }
}
