//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int sliderID { get; set; }
        public string sldH5 { get; set; }
        public string sldH1 { get; set; }
        public string sldContent { get; set; }
        public string sldImage { get; set; }
        public string sldDescription { get; set; }
        public Nullable<System.DateTime> sldCreateDate { get; set; }
        public Nullable<System.DateTime> sldModifierDate { get; set; }
        public Nullable<int> sldCreateUser { get; set; }
        public Nullable<int> ModifierUser { get; set; }
    }
}
