//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int statusID { get; set; }
        public string stsName { get; set; }
        public string stsDescription { get; set; }
        public Nullable<System.DateTime> stsCreateDate { get; set; }
        public Nullable<System.DateTime> stsModifierDate { get; set; }
        public Nullable<int> stsCreateUser { get; set; }
        public Nullable<int> stsModifierUser { get; set; }
    }
}
