//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTquanlyNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int unitID { get; set; }
        public string untName { get; set; }
        public string untDescription { get; set; }
        public Nullable<System.DateTime> untCreateDate { get; set; }
        public Nullable<System.DateTime> untModifierDate { get; set; }
        public Nullable<int> untCreateUser { get; set; }
        public Nullable<int> untModifierUser { get; set; }
    }
}
